# Generated by Django 5.0.6 on 2026-05-26 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_paymenthistory_transaction_id_and_more'),
        ('ai_ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
