# Generated by Django 5.0.6 on 2026-05-21 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('class_test_mark', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quiz_mark', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('final_exam_mark', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('subject_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_results', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': 'Student Results',
                'unique_together': {('student_profile', 'course', 'semester')},
            },
        ),
    ]
