# Generated by Django 5.0.6 on 2026-05-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_paymenthistory_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CLASSROOM', 'Classroom Resource / Lecture Notes'), ('DESKTOP_APP', 'Desktop Application'), ('MOBILE_APP', 'Mobile Application'), ('CODING_TOOL', 'Coding & ML Tools'), ('CRACK_SOFTWARE', 'Third-Party Software (Free/Crack)'), ('INTERVIEW_GUIDE', 'Interview & Career Guide')], default='CLASSROOM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, max_length=500, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
