# Generated by Django 5.0.6 on 2026-05-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_resourcehub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
    ]
