# Generated by Django 5.0.6 on 2026-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_paymenthistory_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
