# Generated by Django 5.0.6 on 2026-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_rename_course_title_course_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehub',
            name='resource_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resourcehub',
            name='category',
            field=models.CharField(choices=[('SOFTWARE', 'Software Engineering'), ('DATA_SCIENCE', 'Data Science & ML'), ('CYBER_SECURITY', 'Cyber Security'), ('GENERAL', 'General Academic'), ('CLASSROOM', 'Classroom Resource / Lecture Notes'), ('DESKTOP_APP', 'Desktop Application'), ('MOBILE_APP', 'Mobile Application'), ('CODING_TOOL', 'Coding & ML Tools'), ('CRACK_SOFTWARE', 'Third-Party Software (Free/Crack)'), ('INTERVIEW_GUIDE', 'Interview & Career Guide')], default='GENERAL', max_length=20),
        ),
    ]
