# Generated by Django 5.0.6 on 2026-06-09 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_resourcehub_resource_url_alter_resourcehub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPracticalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=200)),
                ('tools_learned', models.TextField(blank=True, help_text='যেমন: VS Code, Git, MS PowerPoint', null=True)),
                ('project_outcome', models.TextField(blank=True, help_text='এই সাবজেক্টে প্র্যাকটিক্যালি কী প্রজেক্ট বা কাজ করেছেন?', null=True)),
                ('skill_gaps_declared', models.TextField(blank=True, help_text='আপনার কী কী গ্যাপ রয়ে গেছে? (যেমন: ইংরেজি বলা, স্লাইড বানানো, প্রেজেন্টেশন বা কোডিং)', null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_logs', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Practical Log',
                'verbose_name_plural': 'Student Practical Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
